//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _20140624135850_The_crew_capa_oficial {
            get {
                object obj = ResourceManager.GetObject("20140624135850!The_crew_capa_oficial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _279168_Papel_de_Parede_Logo_Playstation_3_1920x1200 {
            get {
                object obj = ResourceManager.GetObject("279168_Papel-de-Parede-Logo-Playstation-3_1920x1200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _279168_Papel_de_Parede_Logo_Playstation_3_1920x12001 {
            get {
                object obj = ResourceManager.GetObject("279168_Papel-de-Parede-Logo-Playstation-3_1920x12001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _620x350xxboxone_jpg_pagespeed_ic_P3ZuVwdJh3 {
            get {
                object obj = ResourceManager.GetObject("620x350xxboxone.jpg.pagespeed.ic.P3ZuVwdJh3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Assassin_s_Creed___Rogue {
            get {
                object obj = ResourceManager.GetObject("Assassin\'s Creed - Rogue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Background_Xbox_3602 {
            get {
                object obj = ResourceManager.GetObject("Background-Xbox-3602", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Call_of_Duty_Advanced_Warfare_p_games {
            get {
                object obj = ResourceManager.GetObject("Call-of-Duty-Advanced-Warfare-p-games", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Call_of_Duty_Advanced_Warfare_p_games1 {
            get {
                object obj = ResourceManager.GetObject("Call-of-Duty-Advanced-Warfare-p-games1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cópia__2__de_ps4_assassin_s_creed_unity_capa_1 {
            get {
                object obj = ResourceManager.GetObject("Cópia (2) de ps4_assassin_s_creed_unity_capa_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cópia__2__de_ps4_assassin_s_creed_uppnity_capa_1 {
            get {
                object obj = ResourceManager.GetObject("Cópia (2) de ps4_assassin_s_creed_uppnity_capa_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cópia_de_ps4_assassin_s_creed_unity_capa_1 {
            get {
                object obj = ResourceManager.GetObject("Cópia de ps4_assassin_s_creed_unity_capa_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Far_Cry_4 {
            get {
                object obj = ResourceManager.GetObject("Far-Cry-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Far_Cry_41 {
            get {
                object obj = ResourceManager.GetObject("Far-Cry-41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ffe18bc07f4987eed129481171683dad {
            get {
                object obj = ResourceManager.GetObject("ffe18bc07f4987eed129481171683dad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GTA_V_Capa_Brasil_Xbox360 {
            get {
                object obj = ResourceManager.GetObject("GTA-V-Capa-Brasil-Xbox360", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gta_v_five_logo_black_green_612_hd_1680x1050 {
            get {
                object obj = ResourceManager.GetObject("gta-v-five-logo-black-green-612-hd-1680x1050", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gta_v_five_logo_black_green_612_hd_1680x10501 {
            get {
                object obj = ResourceManager.GetObject("gta-v-five-logo-black-green-612-hd-1680x10501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gta_v_xbox_one_capa_jony_games {
            get {
                object obj = ResourceManager.GetObject("gta_v_xbox_one_capa_jony_games", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leandro_cirilo_12far_cry_4_1400170779522_600x843 {
            get {
                object obj = ResourceManager.GetObject("leandro.cirilo.12far-cry-4-1400170779522_600x843", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap male_user_silhouette_318_35708 {
            get {
                object obj = ResourceManager.GetObject("male-user-silhouette_318-35708", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maxresdefallllult {
            get {
                object obj = ResourceManager.GetObject("maxresdefallllult", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maxresdefallllult1 {
            get {
                object obj = ResourceManager.GetObject("maxresdefallllult1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maxresdefault {
            get {
                object obj = ResourceManager.GetObject("maxresdefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap meta_thumb_01ac5074 {
            get {
                object obj = ResourceManager.GetObject("meta-thumb-01ac5074", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap news_sony_ps4_logo {
            get {
                object obj = ResourceManager.GetObject("news_sony_ps4_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PS4_Background {
            get {
                object obj = ResourceManager.GetObject("PS4-Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PS4_icons_playstation_672x372 {
            get {
                object obj = ResourceManager.GetObject("PS4-icons-playstation-672x372", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap the_crew_bf_game_wallpaper_1920 {
            get {
                object obj = ResourceManager.GetObject("the_crew_bf_game_wallpaper_1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wacu1 {
            get {
                object obj = ResourceManager.GetObject("wacu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XBOX_1024x1024 {
            get {
                object obj = ResourceManager.GetObject("XBOX-1024x1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Xbox_360_5 {
            get {
                object obj = ResourceManager.GetObject("Xbox 360 5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XBOX_360_svg {
            get {
                object obj = ResourceManager.GetObject("XBOX_360.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xbox_one_wallpaper_1024x768 {
            get {
                object obj = ResourceManager.GetObject("xbox_one-wallpaper-1024x768", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
